name: Build ExcellentShop
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Inject NightCore into Cloud Maven
      run: |
        mvn install:install-file -Dfile=nightcore-2.16.4.jar -DgroupId=su.nightexpress.nightcore -DartifactId=main -Dversion=2.16.4 -Dpackaging=jar
        mvn install:install-file -Dfile=nightcore-2.16.4.jar -DgroupId=su.nightexpress.nightcore -DartifactId=spigot -Dversion=2.16.4 -Dpackaging=jar
        
    - name: Build ExcellentShop
      run: mvn clean package
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ExcellentShop
        path: target/*.jar
